# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\3rd_year\second_semester\computer_vision\tasks\task4\CV_4\GUI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


