# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\3rd_year\second_semester\computer_vision\tasks\task4\CV_4\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_graphicsView_1 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.input_graphicsView_1.setObjectName("input_graphicsView_1")
        self.gridLayout_2.addWidget(self.input_graphicsView_1, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.output_graphicsView_1 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.output_graphicsView_1.setObjectName("output_graphicsView_1")
        self.gridLayout_3.addWidget(self.output_graphicsView_1, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem, 16, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_18.addItem(spacerItem1, 1, 0, 1, 1)
        self.number_of_classes_slider = QtWidgets.QSlider(self.groupBox)
        self.number_of_classes_slider.setOrientation(QtCore.Qt.Horizontal)
        self.number_of_classes_slider.setObjectName("number_of_classes_slider")
        self.gridLayout_18.addWidget(self.number_of_classes_slider, 14, 0, 1, 1)
        self.thresholdCombox = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thresholdCombox.setFont(font)
        self.thresholdCombox.setObjectName("thresholdCombox")
        self.thresholdCombox.addItem("")
        self.thresholdCombox.addItem("")
        self.thresholdCombox.addItem("")
        self.gridLayout_18.addWidget(self.thresholdCombox, 4, 0, 1, 1)
        self.block_size_val_label = QtWidgets.QLabel(self.groupBox)
        self.block_size_val_label.setObjectName("block_size_val_label")
        self.gridLayout_18.addWidget(self.block_size_val_label, 12, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_17.addWidget(self.label_21, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.browseButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.browseButton_1.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        self.browseButton_1.setFont(font)
        self.browseButton_1.setStyleSheet("QPushButton{\n"
"background-color: #008000; /* Changed to green */\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #006400; /* Darker green */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #004d00; /* Even darker green */\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #006400;\n"
"                    color: #006400;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.browseButton_1.setObjectName("browseButton_1")
        self.gridLayout_15.addWidget(self.browseButton_1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem2, 0, 1, 1, 1)
        self.apply_btn = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        self.apply_btn.setFont(font)
        self.apply_btn.setStyleSheet("QPushButton{\n"
"background-color: #4488bb; /* Changed to #4488bb */\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #336688; /* Darker shade of #4488bb */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #224466; /* Even darker shade of #4488bb */\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #336688;\n"
"                    color: #336688;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.apply_btn.setObjectName("apply_btn")
        self.gridLayout_15.addWidget(self.apply_btn, 0, 2, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_15, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_17.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.block_size_slider = QtWidgets.QSlider(self.groupBox)
        self.block_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.block_size_slider.setObjectName("block_size_slider")
        self.gridLayout_18.addWidget(self.block_size_slider, 9, 0, 1, 1)
        self.select_block_size_label = QtWidgets.QLabel(self.groupBox)
        self.select_block_size_label.setObjectName("select_block_size_label")
        self.gridLayout_18.addWidget(self.select_block_size_label, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_18.addItem(spacerItem4, 3, 0, 1, 1)
        self.select_number_of_classes_label = QtWidgets.QLabel(self.groupBox)
        self.select_number_of_classes_label.setObjectName("select_number_of_classes_label")
        self.gridLayout_18.addWidget(self.select_number_of_classes_label, 13, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_18.addItem(spacerItem5, 5, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_16.addWidget(self.radioButton, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_16.addWidget(self.label_23, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_16.addWidget(self.radioButton_2, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_16.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_16, 6, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 2, 0, 1, 1)
        self.number_of_classes_val_label = QtWidgets.QLabel(self.groupBox)
        self.number_of_classes_val_label.setObjectName("number_of_classes_val_label")
        self.gridLayout_18.addWidget(self.number_of_classes_val_label, 15, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.input_graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_10)
        self.input_graphicsView_2.setObjectName("input_graphicsView_2")
        self.gridLayout_13.addWidget(self.input_graphicsView_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.output_graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_11)
        self.output_graphicsView_2.setObjectName("output_graphicsView_2")
        self.gridLayout_14.addWidget(self.output_graphicsView_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox_12.setMaximumSize(QtCore.QSize(280, 16777215))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_12)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"    background: #bc9d43; /* Changed to gray */\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #bc9d43; /* Changed to white */\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 20px; /* Adjusted to a medium size */\n"
"    height: 20px; /* Adjusted to a medium size */\n"
"    margin: -6px 0; /* Adjusted the margin to properly position the medium-sized handle within the groove */\n"
"    border-radius: 10px; /* Half of the width and height to make it spherical */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #bc9d43; /* Changed to white */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #bc9d43; /* Changed to white */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"   background: #d3d3d3; /* Changed to white */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"   background: #bc9d43; /* Changed to gray */\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_21.addWidget(self.horizontalSlider, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setObjectName("label_4")
        self.gridLayout_21.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_21, 8, 0, 1, 1)
        self.segmentationCombox = QtWidgets.QComboBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.segmentationCombox.setFont(font)
        self.segmentationCombox.setObjectName("segmentationCombox")
        self.segmentationCombox.addItem("")
        self.segmentationCombox.addItem("")
        self.segmentationCombox.addItem("")
        self.segmentationCombox.addItem("")
        self.gridLayout_24.addWidget(self.segmentationCombox, 4, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.gridLayout_24.addLayout(self.formLayout_2, 7, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_24.addItem(spacerItem8, 6, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_24.addItem(spacerItem9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_24.addItem(spacerItem10, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_24.addWidget(self.label_28, 2, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_22.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.browseButton_2 = QtWidgets.QPushButton(self.groupBox_12)
        self.browseButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        self.browseButton_2.setFont(font)
        self.browseButton_2.setStyleSheet("QPushButton{\n"
"background-color: #008000; /* Changed to green */\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #006400; /* Darker green */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #004d00; /* Even darker green */\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #006400;\n"
"                    color: #006400;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.browseButton_2.setObjectName("browseButton_2")
        self.gridLayout_23.addWidget(self.browseButton_2, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_23, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_22.addItem(spacerItem12, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_12)
        self.horizontalSlider_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"    background: #bc9d43; /* Changed to gray */\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #bc9d43; /* Changed to white */\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 20px; /* Adjusted to a medium size */\n"
"    height: 20px; /* Adjusted to a medium size */\n"
"    margin: -6px 0; /* Adjusted the margin to properly position the medium-sized handle within the groove */\n"
"    border-radius: 10px; /* Half of the width and height to make it spherical */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #bc9d43; /* Changed to white */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #bc9d43; /* Changed to white */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"   background: #d3d3d3; /* Changed to white */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"   background: #bc9d43; /* Changed to gray */\n"
"}\n"
"")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_20.addWidget(self.horizontalSlider_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setObjectName("label_3")
        self.gridLayout_20.addWidget(self.label_3, 0, 1, 1, 1)
        self.Apply_pushButton = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        self.Apply_pushButton.setFont(font)
        self.Apply_pushButton.setStyleSheet("QPushButton{\n"
"background-color: #4488bb; /* Changed to #4488bb */\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #336688; /* Darker shade of #4488bb */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #224466; /* Even darker shade of #4488bb */\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #336688;\n"
"                    color: #336688;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.Apply_pushButton.setObjectName("Apply_pushButton")
        self.gridLayout_20.addWidget(self.Apply_pushButton, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_20, 10, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_24.addItem(spacerItem13, 5, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem14)
        self.gridLayout_24.addLayout(self.formLayout, 9, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem15, 11, 0, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_12, 0, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.input_graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_13)
        self.input_graphicsView_3.setObjectName("input_graphicsView_3")
        self.gridLayout_27.addWidget(self.input_graphicsView_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.output_graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_14)
        self.output_graphicsView_3.setObjectName("output_graphicsView_3")
        self.gridLayout_28.addWidget(self.output_graphicsView_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setMinimumSize(QtCore.QSize(280, 0))
        self.groupBox_15.setMaximumSize(QtCore.QSize(280, 16777215))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_27 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_32.addWidget(self.label_27, 3, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_32.addItem(spacerItem16, 0, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.browseButton_3 = QtWidgets.QPushButton(self.groupBox_15)
        self.browseButton_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        self.browseButton_3.setFont(font)
        self.browseButton_3.setStyleSheet("QPushButton{\n"
"background-color: #008000; /* Changed to green */\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #006400; /* Darker green */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #004d00; /* Even darker green */\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #006400;\n"
"                    color: #006400;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.browseButton_3.setObjectName("browseButton_3")
        self.gridLayout_33.addWidget(self.browseButton_3, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem17, 0, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_33, 4, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_32.addItem(spacerItem18, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.gridLayout_32.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_32, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem19, 6, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.gridLayout_30.addLayout(self.formLayout_3, 1, 0, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_30.addLayout(self.gridLayout_31, 2, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.gridLayout_30.addLayout(self.formLayout_4, 3, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.Apply_pushButton_2 = QtWidgets.QPushButton(self.groupBox_15)
        font = QtGui.QFont()
        font.setFamily("-apple-system,system-ui,Segoe UI,Roboto,Helvetica Neue,Ubuntu,sans-serif")
        self.Apply_pushButton_2.setFont(font)
        self.Apply_pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: #4488bb; /* Changed to #4488bb */\n"
"border-radius: 15px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"font-size: 100%;\n"
"height: 30px;\n"
"line-height: 1.15;\n"
"outline: none;\n"
"padding: 3 10px;\n"
"text-align: center;\n"
"width: 30px; /* Reduced width to 200 pixels */\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #336688; /* Darker shade of #4488bb */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #224466; /* Even darker shade of #4488bb */\n"
"}\n"
"QPushButton:focus {\n"
"                    border-color: #336688;\n"
"                    color: #336688;\n"
"                    outline: none;\n"
"}\n"
"QPushButton.dark:hover {\n"
"                    background-color: #17222d; /* Adjust dark mode hover background color */\n"
"}\n"
"\n"
"QPushButton.dark:pressed {\n"
"                    background-color: #0f1417; /* Adjust dark mode pressed background color */\n"
"}\n"
"")
        self.Apply_pushButton_2.setObjectName("Apply_pushButton_2")
        self.gridLayout_34.addWidget(self.Apply_pushButton_2, 0, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem20, 0, 1, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_34, 5, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_30.addItem(spacerItem21, 4, 0, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input Image"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output Image"))
        self.thresholdCombox.setItemText(0, _translate("MainWindow", "Optimal Thresholding"))
        self.thresholdCombox.setItemText(1, _translate("MainWindow", "Spectral Thresholding"))
        self.thresholdCombox.setItemText(2, _translate("MainWindow", "Otsu Thresholding"))
        self.block_size_val_label.setText(_translate("MainWindow", "block size = 0"))
        self.label_21.setText(_translate("MainWindow", "Browse Image"))
        self.browseButton_1.setText(_translate("MainWindow", "Browse"))
        self.apply_btn.setText(_translate("MainWindow", "Apply"))
        self.select_block_size_label.setText(_translate("MainWindow", "select block size"))
        self.select_number_of_classes_label.setText(_translate("MainWindow", "select nubmer of classes"))
        self.radioButton.setText(_translate("MainWindow", "Local "))
        self.label_23.setText(_translate("MainWindow", "Threshold Type"))
        self.radioButton_2.setText(_translate("MainWindow", "Global"))
        self.label_22.setText(_translate("MainWindow", "Choose Mode"))
        self.number_of_classes_val_label.setText(_translate("MainWindow", "number of classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Thresholding"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Input Image"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Output Image"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.segmentationCombox.setItemText(0, _translate("MainWindow", "K-means Segmentation"))
        self.segmentationCombox.setItemText(1, _translate("MainWindow", "Mean-Shift Segmentation"))
        self.segmentationCombox.setItemText(2, _translate("MainWindow", "Agglomerative"))
        self.segmentationCombox.setItemText(3, _translate("MainWindow", "Region Growing"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "Choose Mode"))
        self.label_26.setText(_translate("MainWindow", "Browse Image"))
        self.browseButton_2.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.Apply_pushButton.setText(_translate("MainWindow", "Apply"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Segmentation"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Input Image"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Output Image"))
        self.label_27.setText(_translate("MainWindow", "Browse Image"))
        self.browseButton_3.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "  LUV Converter"))
        self.Apply_pushButton_2.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "LUV Converter"))
