# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\3rd_year\second_semester\computer_vision\tasks\task1\task1\filtering&edge detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem = QtWidgets.QSpacerItem(7, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_19.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(7, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_19.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.original_image = QtWidgets.QGraphicsView(self.groupBox)
        self.original_image.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.original_image.setObjectName("original_image")
        self.gridLayout.addWidget(self.original_image, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_3.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_2.addWidget(self.graphicsView_3, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_2, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.groupBox_5)
        self.graphicsView_12.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.gridLayout_8.addWidget(self.graphicsView_12, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_7.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.gridLayout_9.addWidget(self.graphicsView_7, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_7, 5, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView_4.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_5.addWidget(self.graphicsView_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView_5.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_6.addWidget(self.graphicsView_5, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_2, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_4, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 2, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_3, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_15, 0, 3, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setMaximumSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setContentsMargins(12, 0, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.image_1 = QtWidgets.QGraphicsView(self.groupBox_7)
        self.image_1.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.image_1.setObjectName("image_1")
        self.gridLayout_11.addWidget(self.image_1, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setMaximumSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.image_2 = QtWidgets.QGraphicsView(self.groupBox_8)
        self.image_2.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.image_2.setObjectName("image_2")
        self.gridLayout_12.addWidget(self.image_2, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setMaximumSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.groupBox_9)
        self.graphicsView_10.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.gridLayout_13.addWidget(self.graphicsView_10, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_14, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem6, 0, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.histogram = PlotWidget(self.groupBox_10)
        self.histogram.setMinimumSize(QtCore.QSize(200, 161))
        self.histogram.setObjectName("histogram")
        self.gridLayout_28.addWidget(self.histogram, 0, 2, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.distribution_curve = PlotWidget(self.groupBox_11)
        self.distribution_curve.setMinimumSize(QtCore.QSize(200, 161))
        self.distribution_curve.setObjectName("distribution_curve")
        self.gridLayout_29.addWidget(self.distribution_curve, 0, 2, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setMinimumSize(QtCore.QSize(661, 0))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.RGB_histogram_dist_curve = PlotWidget(self.groupBox_12)
        self.RGB_histogram_dist_curve.setMinimumSize(QtCore.QSize(637, 439))
        self.RGB_histogram_dist_curve.setObjectName("RGB_histogram_dist_curve")
        self.gridLayout_31.addWidget(self.RGB_histogram_dist_curve, 0, 2, 1, 1)
        self.gridLayout_35.addWidget(self.groupBox_12, 1, 0, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_35, 0, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setStyleSheet("")
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.plot_widget_2 = PlotWidget(self.groupBox_14)
        self.plot_widget_2.setMinimumSize(QtCore.QSize(200, 161))
        self.plot_widget_2.setObjectName("plot_widget_2")
        self.gridLayout_33.addWidget(self.plot_widget_2, 0, 2, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.plot_widget = PlotWidget(self.groupBox_13)
        self.plot_widget.setMinimumSize(QtCore.QSize(200, 161))
        self.plot_widget.setObjectName("plot_widget")
        self.gridLayout_32.addWidget(self.plot_widget, 0, 2, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_34, 0, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_36, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_23.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Original Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filtered Image"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Global Thresholding"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Local Thresholding"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Equalization"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Normalization"))
        self.label.setText(_translate("MainWindow", "Add Noise"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Uniform"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Salt & Pepper"))
        self.label_2.setText(_translate("MainWindow", "Add Smooth filter"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Average"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Median"))
        self.label_4.setText(_translate("MainWindow", "Edge detection filter"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Sobel"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Roberts"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Prewitt"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Canny"))
        self.label_3.setText(_translate("MainWindow", "Frequency domain filter"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Low Pass"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "High Pass"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Image1"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Image2"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Hybrid Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Histogram"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Distribution Curve"))
        self.groupBox_12.setTitle(_translate("MainWindow", "RGB Histogram and Distribution Curve "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
from pyqtgraph import PlotWidget
