# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\3rd_year\second_semester\computer_vision\tasks\task1\task1\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.equalization = QtWidgets.QGraphicsView(self.groupBox_3)
        self.equalization.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.equalization.setObjectName("equalization")
        self.gridLayout_5.addWidget(self.equalization, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.normalization = QtWidgets.QGraphicsView(self.groupBox_4)
        self.normalization.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.normalization.setObjectName("normalization")
        self.gridLayout_6.addWidget(self.normalization, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(7, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_19.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.original_image = QtWidgets.QGraphicsView(self.groupBox)
        self.original_image.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.original_image.setObjectName("original_image")
        self.gridLayout.addWidget(self.original_image, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filtered_image = QtWidgets.QGraphicsView(self.groupBox_2)
        self.filtered_image.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.filtered_image.setObjectName("filtered_image")
        self.gridLayout_2.addWidget(self.filtered_image, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_2, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.global_thresholding = QtWidgets.QGraphicsView(self.groupBox_5)
        self.global_thresholding.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.global_thresholding.setObjectName("global_thresholding")
        self.gridLayout_8.addWidget(self.global_thresholding, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.local_thresholding = QtWidgets.QGraphicsView(self.groupBox_6)
        self.local_thresholding.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.local_thresholding.setObjectName("local_thresholding")
        self.gridLayout_9.addWidget(self.local_thresholding, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_7, 5, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.noise_combo = QtWidgets.QComboBox(self.widget)
        self.noise_combo.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.noise_combo.setObjectName("noise_combo")
        self.noise_combo.addItem("")
        self.noise_combo.addItem("")
        self.noise_combo.addItem("")
        self.noise_combo.addItem("")
        self.gridLayout_3.addWidget(self.noise_combo, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 0, 1, 1)
        self.filter_combo = QtWidgets.QComboBox(self.widget)
        self.filter_combo.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.filter_combo.setObjectName("filter_combo")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.filter_combo.addItem("")
        self.gridLayout_10.addWidget(self.filter_combo, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 0, 0, 1, 1)
        self.edge_combo = QtWidgets.QComboBox(self.widget)
        self.edge_combo.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.edge_combo.setObjectName("edge_combo")
        self.edge_combo.addItem("")
        self.edge_combo.addItem("")
        self.edge_combo.addItem("")
        self.edge_combo.addItem("")
        self.edge_combo.addItem("")
        self.gridLayout_16.addWidget(self.edge_combo, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 2, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.freq_filter_combo = QtWidgets.QComboBox(self.widget)
        self.freq_filter_combo.setStyleSheet("QComboBox {\n"
"    border: 1px solid #565656; /* Border color for the combobox */\n"
"    border-radius: 10px;\n"
"    padding: 2px 18px 2px 8px; /* Adjust padding as needed */\n"
"    background-color: rgb(45, 73, 84); /* Background color of the combobox */\n"
"    color: #FFFFFF; /* Text color */\n"
"    selection-background-color: #2A2A2A; /* Background color when an item is selected */\n"
"    font-family: \"Overpass\", sans-serif; /* Set the desired font-family */\n"
"    font-weight:bold;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgb(127, 127, 127); /* Border color on hover */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0;\n"
"    border: none;\n"
"    margin-right: 6px; /* Adjust as needed */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 8px;\n"
"    background-color: #363636; /* Background color of each item */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: rgb(42, 42, 42); /* Background color of the selected item */\n"
"}\n"
"\n"
"QComboBox::item:hover {\n"
"    background-color: #2A2A2A; /* Background color on item hover */\n"
"}")
        self.freq_filter_combo.setObjectName("freq_filter_combo")
        self.freq_filter_combo.addItem("")
        self.freq_filter_combo.addItem("")
        self.freq_filter_combo.addItem("")
        self.gridLayout_15.addWidget(self.freq_filter_combo, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_15, 0, 3, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(7, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_19.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_20.addLayout(self.gridLayout_14, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem6, 0, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.histogram_graph = QtWidgets.QGraphicsView(self.groupBox_10)
        self.histogram_graph.setObjectName("histogram_graph")
        self.gridLayout_28.addWidget(self.histogram_graph, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.distribution_curve_graph = QtWidgets.QGraphicsView(self.groupBox_11)
        self.distribution_curve_graph.setObjectName("distribution_curve_graph")
        self.gridLayout_29.addWidget(self.distribution_curve_graph, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setMinimumSize(QtCore.QSize(661, 0))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.red_histo_graph = QtWidgets.QGraphicsView(self.groupBox_12)
        self.red_histo_graph.setObjectName("red_histo_graph")
        self.gridLayout_31.addWidget(self.red_histo_graph, 0, 0, 1, 1)
        self.green_histo_graph = QtWidgets.QGraphicsView(self.groupBox_12)
        self.green_histo_graph.setObjectName("green_histo_graph")
        self.gridLayout_31.addWidget(self.green_histo_graph, 1, 0, 1, 1)
        self.blue_histo_graph = QtWidgets.QGraphicsView(self.groupBox_12)
        self.blue_histo_graph.setObjectName("blue_histo_graph")
        self.gridLayout_31.addWidget(self.blue_histo_graph, 2, 0, 1, 1)
        self.gridLayout_35.addWidget(self.groupBox_12, 1, 0, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_35, 0, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setStyleSheet("")
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.cumulative_curve = QtWidgets.QGraphicsView(self.groupBox_14)
        self.cumulative_curve.setObjectName("cumulative_curve")
        self.gridLayout_33.addWidget(self.cumulative_curve, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.red_dist_graph = QtWidgets.QGraphicsView(self.groupBox_13)
        self.red_dist_graph.setObjectName("red_dist_graph")
        self.gridLayout_32.addWidget(self.red_dist_graph, 0, 0, 1, 1)
        self.green_dist_graph = QtWidgets.QGraphicsView(self.groupBox_13)
        self.green_dist_graph.setObjectName("green_dist_graph")
        self.gridLayout_32.addWidget(self.green_dist_graph, 1, 0, 1, 1)
        self.blue_dist_graph = QtWidgets.QGraphicsView(self.groupBox_13)
        self.blue_dist_graph.setObjectName("blue_dist_graph")
        self.gridLayout_32.addWidget(self.blue_dist_graph, 2, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_34, 0, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_36, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setMaximumSize(QtCore.QSize(700, 400))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.image_2 = QtWidgets.QGraphicsView(self.groupBox_8)
        self.image_2.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.image_2.setObjectName("image_2")
        self.gridLayout_12.addWidget(self.image_2, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setMaximumSize(QtCore.QSize(700, 400))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setContentsMargins(12, 0, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.image_1 = QtWidgets.QGraphicsView(self.groupBox_7)
        self.image_1.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.image_1.setObjectName("image_1")
        self.gridLayout_11.addWidget(self.image_1, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_22, 1, 0, 1, 1)
        self.label_hybrid_image = QtWidgets.QLabel(self.tab_3)
        self.label_hybrid_image.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Overpass")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_hybrid_image.setFont(font)
        self.label_hybrid_image.setStyleSheet("QLabel {\n"
"\n"
"  \n"
"    background-color: rgb(70, 100, 120); /* Matching color for the label */\n"
"    color: #FFFFFF;\n"
"    font-family: \"Overpass\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"alignment: center;\n"
"}\n"
"\n"
"\n"
"")
        self.label_hybrid_image.setObjectName("label_hybrid_image")
        self.gridLayout_27.addWidget(self.label_hybrid_image, 0, 0, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem8 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem9, 0, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.hybrid_image = QtWidgets.QGraphicsView(self.groupBox_9)
        self.hybrid_image.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"border-radius:30px;\n"
"}")
        self.hybrid_image.setObjectName("hybrid_image")
        self.gridLayout_13.addWidget(self.hybrid_image, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 1, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_26, 4, 0, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        spacerItem10 = QtWidgets.QSpacerItem(189, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(189, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_24, 2, 0, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_23.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Equalization"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Normalization"))
        self.groupBox.setTitle(_translate("MainWindow", "Original Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filtered Image"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Global Thresholding"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Local Thresholding"))
        self.label.setText(_translate("MainWindow", "Add noise"))
        self.noise_combo.setItemText(0, _translate("MainWindow", "None"))
        self.noise_combo.setItemText(1, _translate("MainWindow", "Uniform"))
        self.noise_combo.setItemText(2, _translate("MainWindow", "Gaussian"))
        self.noise_combo.setItemText(3, _translate("MainWindow", "Salt & Pepper"))
        self.label_2.setText(_translate("MainWindow", "Add smooth filter"))
        self.filter_combo.setItemText(0, _translate("MainWindow", "None"))
        self.filter_combo.setItemText(1, _translate("MainWindow", "Average"))
        self.filter_combo.setItemText(2, _translate("MainWindow", "Gaussian"))
        self.filter_combo.setItemText(3, _translate("MainWindow", "Median"))
        self.label_4.setText(_translate("MainWindow", "Edge detection filter"))
        self.edge_combo.setItemText(0, _translate("MainWindow", "None"))
        self.edge_combo.setItemText(1, _translate("MainWindow", "Sobel"))
        self.edge_combo.setItemText(2, _translate("MainWindow", "Roberts"))
        self.edge_combo.setItemText(3, _translate("MainWindow", "Prewitt"))
        self.edge_combo.setItemText(4, _translate("MainWindow", "Canny"))
        self.label_3.setText(_translate("MainWindow", "Frequency domain filter"))
        self.freq_filter_combo.setItemText(0, _translate("MainWindow", "None"))
        self.freq_filter_combo.setItemText(1, _translate("MainWindow", "Low Pass"))
        self.freq_filter_combo.setItemText(2, _translate("MainWindow", "High Pass"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Tab 1"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Histogram"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Distribution Curve"))
        self.groupBox_12.setTitle(_translate("MainWindow", "RGB Histogram and Distribution Curve "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Image 2"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Image 1"))
        self.label_hybrid_image.setText(_translate("MainWindow", "    Hybrid Image"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Hybrid Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
